version: "3.8"

services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: ../../Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - VECTOR_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    command: ["api"]

volumes:
  postgres_data:
